### ISSUE TITLE
loaddll() does not work with python in debug mode

### ISSUE THREAD

**Issue by adrian-vlad** [irvinren/shared_atomic#3]
When installed with `pip` the compiled library name is not `shared_atomic_.abi3.so`, but `shared_atomic_.cpython-38d-x86_64-linux-gnu.so`. This happens on linux machines when python is compiled from sources in debug mode (`--with-pydebug`).

I found this issue trying to install this library on a development machine which has python compiled in debug mode. For all the other machines that I tried everything was fine.

**Comment by irvinren** [comment]
Looking into this, is it neccesary to use debug mode?

**Comment by irvinren** [comment]
BTW, is it possible to get certificate of adoptation of this project from your company ?

**Comment by adrian-vlad** [comment]
Yes we needed debug mode.

Unfortunately, we dropped the use of your library in favor of a different implementation.

**Comment by irvinren** [comment]
Is there other choices? 16:14, 28 July 2022, "adrian-vlad" ***@***.***>:
Yes we needed debug mode.
Unfortunately, we dropped the use of your library in favor of a different implementation.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
-- Sent from Yandex.Mail for mobile

**Comment by adrian-vlad** [comment]
I don't know what you mean

**Comment by irvinren** [comment]
debug mode not supported

**Comment by irvinren** [comment]
I finally got the chance to look into it, what's the error message you got when you run it in debug mode?

**Comment by irvinren** [comment]
fixed in 2.1.7
